// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageID.proto

#include "messageID.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace Proto {
}  // namespace Proto
void InitDefaults_messageID_2eproto() {
}

constexpr ::google::protobuf::Metadata* file_level_metadata_messageID_2eproto = nullptr;
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors_messageID_2eproto[2];
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_messageID_2eproto = nullptr;
const ::google::protobuf::uint32 TableStruct_messageID_2eproto::offsets[1] = {};
static constexpr ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static constexpr ::google::protobuf::Message* const* file_default_instances = NULL;

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_messageID_2eproto = {
  {}, AddDescriptors_messageID_2eproto, "messageID.proto", schemas,
  file_default_instances, TableStruct_messageID_2eproto::offsets,
  file_level_metadata_messageID_2eproto, 0, file_level_enum_descriptors_messageID_2eproto, file_level_service_descriptors_messageID_2eproto,
};

::google::protobuf::internal::DescriptorTable descriptor_table_messageID_2eproto = {
  false, InitDefaults_messageID_2eproto, 
  "\n\017messageID.proto\022\005Proto*\212\001\n\nMESSAGE_ID\022"
  "\024\n\020MSGID_HEART_BEAT\020\000\022\021\n\rMSGID_LOGIN_C\020e"
  "\022\021\n\rMSGID_LOGIN_S\020f\022\022\n\016MSGID_LOGOFF_C\020g\022"
  "\022\n\016MSGID_LOGOFF_S\020h\022\030\n\024MSGID_FORCE_QUIT_"
  "NTF\020i*\215\001\n\tRESULT_ID\022\022\n\016RESULT_SUCCESS\020\000\022"
  "\030\n\024RESULT_LOGIN_NOEXIST\020e\022\031\n\025RESULT_LOGI"
  "N_REPEATED\020f\022\034\n\030RESULT_LOGOFF_OTHERPLACE"
  "\020g\022\031\n\025RESULT_LOGOFF_SEALOFF\020hb\006proto3"
,
  "messageID.proto", &assign_descriptors_table_messageID_2eproto, 317,
};

void AddDescriptors_messageID_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_messageID_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_messageID_2eproto = []() { AddDescriptors_messageID_2eproto(); return true; }();
namespace Proto {
const ::google::protobuf::EnumDescriptor* MESSAGE_ID_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_messageID_2eproto);
  return file_level_enum_descriptors_messageID_2eproto[0];
}
bool MESSAGE_ID_IsValid(int value) {
  switch (value) {
    case 0:
    case 101:
    case 102:
    case 103:
    case 104:
    case 105:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* RESULT_ID_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_messageID_2eproto);
  return file_level_enum_descriptors_messageID_2eproto[1];
}
bool RESULT_ID_IsValid(int value) {
  switch (value) {
    case 0:
    case 101:
    case 102:
    case 103:
    case 104:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
